---
- name: Install php-fpm and deps
  apt: name=php5-fpm state=present

- name: Disable default pool
  command: mv /etc/php5/fpm/pool.d/www.conf /etc/php5/fpm/pool.d/www.disabled creates=/etc/php5/fpm/pool.d/www.disabled
  notify: restart php-fpm

- name: Copy php-fpm configuration
  template: src=www.conf dest=/etc/php5/fpm/pool.d/www.conf
  notify: restart php-fpm
